#!/bin/bash
#Menu

echo -e "* menu      : menampilkan daftar perintah"
echo -e "* buat      : membuat akun"
echo -e "* tambah    : menambah masa aktif akun"
echo -e "* trial     : membuat akun trial"
echo -e "* hapusxp   : menghapus akun expired"
echo -e "* hapus     : menghapus akun"
echo -e "* cek       : cek user login"
echo -e "* member    : daftar member"
echo -e "* resvis    : restart service dropbear, webmin"
echo -e "              squid3, OpenVPN dan SSH"
echo -e "* reboot    : reboot VPS"
echo -e "* speedtest : speedtest VPS"
echo -e "* info      : menampilkan informasi sistem"
echo -e "* about     : info script auto install"
echo -e "* exit      : keluar dari Putty/Connecbot/"
echo -e "              JuiceSSH"
echo -e ""
